---
- name: Agregar en sysctl.conf
  hosts: all
  become: yes
  tasks:
    - name: Respaldo previo
      shell: mv /etc/sysctl.conf /etc/sysctl.conf-bk
      ignore_errors: yes

    - name: Creación del archivo
      shell: touch /etc/sysctl.conf

    - name: Agregar info a sysctl.conf
      lineinfile:
        dest: /etc/sysctl.conf
        line: 'net.ipv4.tcp_max_syn_backlog = 4096'

    - name: Agregar info a sysctl.conf
      lineinfile:
        dest: /etc/sysctl.conf
        line: 'net.ipv4.tcp_tw_reuse=1'

    - name: Agregar info a sysctl.conf
      lineinfile:
        dest: /etc/sysctl.conf
        line: 'net.ipv4.tcp_tw_recycle=1'

    - name: Agregar info a sysctl.conf
      lineinfile:
        dest: /etc/sysctl.conf
        line: 'net.ipv4.tcp_syncookies = 1'

    - name: Agregar info a sysctl.conf
      lineinfile:
        dest: /etc/sysctl.conf
        line: 'net.core.somaxconn = 1024'

    - name: Agregar info a sysctl.conf
      lineinfile:
        dest: /etc/sysctl.conf
        line: 'net.ipv6.conf.all.disable_ipv6 = 1'

    - name: Agregar info a sysctl.conf
      lineinfile:
        dest: /etc/sysctl.conf
        line: 'net.ipv6.conf.default.disable_ipv6 = 1'

    - name: Agregar info a sysctl.conf
      lineinfile:
        dest: /etc/sysctl.conf
        line: 'vm.swappiness = 0'

    - name: Lectura desde el archivo
      shell: sysctl -p
